# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Armstrong Web Development
email: armstrongwebdev@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Armstrong Web Development provides professional website design and hosting services for small businesses. We specialize in creating custom websites that are mobile-friendly, SEO-optimized, and tailored to your specific needs. Secure and reliable web hosting included. Increase your online visibility and attract new customers with our affordable website solutions. Contact us for a free consultation.
baseurl: "" # the subpath of your site, e.g. /blog
url: "AWD-2069.github.io" # the base hostname & protocol for your site
github_username:  AWD-2069

# Build settings
markdown: kramdown
